sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # Saat kita meng-encrypt file keypair.json dari GCP (dengan Travis CLI), Travis CLI akan men-generate script di 1 baris bawah ini
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  
  # Install GCP SDK di Travis
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  - gcloud components update kubectl
  # "activate-service-account" itu seperti IAM di AWS | "service-account.json" akan kita generate             
  - gcloud auth activate-service-account --key-file service-account.json

  # Masukan ID nama project di GCP (ingat, bukan nama project)
  - gcloud config set project u-kubernetes
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials u-kubernetes-cluster

  # Masukan Docker Hub username dan password sebagai environment variable di Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true USERNAME/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
