apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: senzdamsikubernetes-xyz-tls
spec:
  secretName: senzdamsikubernetes-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: senzdamsikubernetes.xyz
  dnsNames:
    - senzdamsikubernetes.xyz
    - www.senzdamsikubernetes.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - senzdamsikubernetes.xyz
          - www.senzdamsikubernetes.xyz
